import { MasterDataKebun, RequestKebun, NotificationItem, UserProfile, calculateKebunTotals } from '@/types/database.types';

export const REGIONAL_LIST = [
  { key: 'aceh', name: 'Regional Aceh', cro: 'CRO I', email: 'maker.aceh@agridam.co.id' },
  { key: 'sumut1', name: 'Regional Sumut 1', cro: 'CRO I', email: 'maker.sumut1@agridam.co.id' },
  { key: 'sumut2', name: 'Regional Sumut 2', cro: 'CRO I', email: 'maker.sumut2@agridam.co.id' },
  { key: 'riau1', name: 'Regional Riau 1', cro: 'CRO II', email: 'maker.riau1@agridam.co.id' },
  { key: 'riau2', name: 'Regional Riau 2', cro: 'CRO III', email: 'maker.riau2@agridam.co.id' },
  { key: 'riau3', name: 'Regional Riau 3', cro: 'CRO III', email: 'maker.riau3@agridam.co.id' },
  { key: 'riau4', name: 'Regional Riau 4', cro: 'CRO IV', email: 'maker.riau4@agridam.co.id' },
  { key: 'babel', name: 'Regional Babel', cro: 'CRO V', email: 'maker.babel@agridam.co.id' },
  { key: 'jambi', name: 'Regional Jambi', cro: 'CRO V', email: 'maker.jambi@agridam.co.id' },
  { key: 'sumbar', name: 'Regional Sumbar', cro: 'CRO V', email: 'maker.sumbar@agridam.co.id' },
  { key: 'sumsel', name: 'Regional Sumsel', cro: 'CRO V', email: 'maker.sumsel@agridam.co.id' },
  { key: 'kalbar1', name: 'Regional Kalbar 1', cro: 'CRO VI', email: 'maker.kalbar1@agridam.co.id' },
  { key: 'kalbar2', name: 'Regional Kalbar 2', cro: 'CRO VI', email: 'maker.kalbar2@agridam.co.id' },
  { key: 'kalsel1', name: 'Regional Kalsel 1', cro: 'CRO VII', email: 'maker.kalsel1@agridam.co.id' },
  { key: 'kalsel2', name: 'Regional Kalsel 2', cro: 'CRO VII', email: 'maker.kalsel2@agridam.co.id' },
  { key: 'kaltara', name: 'Regional Kaltara', cro: 'CRO VII', email: 'maker.kaltara@agridam.co.id' },
  { key: 'kaltim', name: 'Regional Kaltim', cro: 'CRO VII', email: 'maker.kaltim@agridam.co.id' },
  { key: 'kalteng1', name: 'Regional Kalteng 1', cro: 'CRO VIII', email: 'maker.kalteng1@agridam.co.id' },
  { key: 'kalteng3', name: 'Regional Kalteng 3', cro: 'CRO VIII', email: 'maker.kalteng3@agridam.co.id' },
  { key: 'kalteng2', name: 'Regional Kalteng 2', cro: 'CRO IX', email: 'maker.kalteng2@agridam.co.id' },
  { key: 'sulteng', name: 'Regional Sulteng', cro: 'CRO X', email: 'maker.sulteng@agridam.co.id' },
  { key: 'sultra', name: 'Regional Sultra', cro: 'CRO X', email: 'maker.sultra@agridam.co.id' }
];

export const DEMO_USERS: Record<string, UserProfile> = {
  exec: {
    id: 'user-exec-001',
    email: 'executive@agridam.co.id',
    full_name: 'Executive Management',
    role: 'executive',
    regional_name: 'Head Office (Jakarta)',
    cro_name: 'Board of Directors'
  },
  ho: {
    id: 'user-ho-001',
    email: 'ADMIN',
    full_name: 'Admin Head Office (Checker Pusat)',
    role: 'ho',
    regional_name: 'Head Office (Jakarta)',
    cro_name: 'HO National'
  },
  ...Object.fromEntries(
    REGIONAL_LIST.map((reg) => [
      reg.key,
      {
        id: `user-reg-${reg.key}`,
        email: reg.email,
        full_name: `Maker ${reg.name}`,
        role: 'regional' as const,
        regional_name: reg.name,
        cro_name: reg.cro
      }
    ])
  )
};

const rawKebunList: Omit<MasterDataKebun, 'created_at' | 'updated_at'>[] = [
  {
    id: 'kebun-001',
    cro: 'CRO 1',
    wilayah: 'Regional Aceh',
    nama_kebun_pt: 'PT Bintang Permata Alue Waki',
    nama_kebun_aktual: 'PT Bintang Permata Alue Waki',
    nama_mitra_vendor: '-',
    kode_tag_kebun: 'PT-BPA-01',
    keterangan: '-',
    tahapan: 'Tahap 4',
    status: 'Belum Dikelola',
    penjelasan: 'Lahan dikuasai oleh masyarakat dan mantan kombatan, Sebahagian lahan telah memiliki sertifikat.',
    luas_ba: 93.54,
    luas_shp_awal: 0,
    ho_planted_inti: 93.54,
    ho_planted_plasma: 0,
    ho_planted_masyarakat: 0,
    ho_tbm: 0,
    ho_areal_lain: 0,
    reg_planted_inti: 93.54,
    reg_planted_plasma: 0,
    reg_planted_masyarakat: 0,
    reg_tbm: 0,
    reg_areal_lain: 0,
    inti_dikuasai: 0,
    inti_tidak_dikuasai: 93.54,
    plasma_dikuasai: 0,
    plasma_tidak_dikuasai: 0,
    masyarakat_dikuasai: 0,
    masyarakat_tidak_dikuasai: 0,
    tbm_dikuasai: 0,
    tbm_tidak_dikuasai: 0,
    provinsi: 'Aceh',
    kabupaten: 'Nagan Raya',
    ...calculateKebunTotals({
      luas_ba: 93.54,
      ho_planted_inti: 93.54,
      reg_planted_inti: 93.54,
      inti_tidak_dikuasai: 93.54
    })
  },
  {
    id: 'kebun-002',
    cro: 'CRO 1',
    wilayah: 'Regional Aceh',
    nama_kebun_pt: 'PT Global Sawit Semesta',
    nama_kebun_aktual: 'PT Global Sawit Semesta',
    nama_mitra_vendor: '-',
    kode_tag_kebun: 'PT-GSS-01',
    keterangan: '-',
    tahapan: 'Tahap 4',
    status: 'Belum Dikelola',
    penjelasan: 'Sudah check ke lokasi 3x, PT ini kooperatif atas penguasaan kembali.',
    luas_ba: 465.46,
    luas_shp_awal: 0,
    ho_planted_inti: 465.46,
    ho_planted_plasma: 0,
    ho_planted_masyarakat: 0,
    ho_tbm: 0,
    ho_areal_lain: 0,
    reg_planted_inti: 50.00,
    reg_planted_plasma: 0,
    reg_planted_masyarakat: 0,
    reg_tbm: 0,
    reg_areal_lain: 415.46,
    inti_dikuasai: 0,
    inti_tidak_dikuasai: 50.00,
    plasma_dikuasai: 0,
    plasma_tidak_dikuasai: 0,
    masyarakat_dikuasai: 0,
    masyarakat_tidak_dikuasai: 0,
    tbm_dikuasai: 0,
    tbm_tidak_dikuasai: 0,
    provinsi: 'Aceh',
    kabupaten: 'Aceh Singkil',
    ...calculateKebunTotals({
      luas_ba: 465.46,
      ho_planted_inti: 465.46,
      reg_planted_inti: 50.00,
      reg_areal_lain: 415.46,
      inti_tidak_dikuasai: 50.00
    })
  },
  {
    id: 'kebun-003',
    cro: 'CRO 1',
    wilayah: 'Regional Sumut 1',
    nama_kebun_pt: 'Koperasi Produsen Maju Bersama',
    nama_kebun_aktual: 'Koperasi Produsen Maju Bersama',
    nama_mitra_vendor: 'Koperasi Produsen Maju Bersama',
    kode_tag_kebun: 'KP-PMB-01',
    keterangan: 'sudah KSO tanggal 21 oktober 2025',
    tahapan: 'Tahap 2',
    status: 'KSO',
    penjelasan: 'Kemitraan KSO berjalan efektif dengan hasil panen stabil',
    luas_ba: 786.00,
    luas_shp_awal: 0,
    ho_planted_inti: 786.00,
    ho_planted_plasma: 0,
    ho_planted_masyarakat: 0,
    ho_tbm: 0,
    ho_areal_lain: 0,
    reg_planted_inti: 786.00,
    reg_planted_plasma: 0,
    reg_planted_masyarakat: 0,
    reg_tbm: 0,
    reg_areal_lain: 0,
    inti_dikuasai: 786.00,
    inti_tidak_dikuasai: 0,
    plasma_dikuasai: 0,
    plasma_tidak_dikuasai: 0,
    masyarakat_dikuasai: 0,
    masyarakat_tidak_dikuasai: 0,
    tbm_dikuasai: 0,
    tbm_tidak_dikuasai: 0,
    provinsi: 'Sumatera Utara',
    kabupaten: 'Labuhan Batu',
    ...calculateKebunTotals({
      luas_ba: 786.00,
      ho_planted_inti: 786.00,
      reg_planted_inti: 786.00,
      inti_dikuasai: 786.00
    })
  },
  {
    id: 'kebun-004',
    cro: 'CRO 6',
    wilayah: 'Regional Kalbar 1 Ex Duta Palma',
    nama_kebun_pt: 'PT Palma Agrolestari West',
    nama_kebun_aktual: 'PT Palma Agrolestari West',
    nama_mitra_vendor: 'PT Agrolestari Mandiri',
    kode_tag_kebun: 'PT-PAL-01',
    keterangan: 'Areal eks-Duta Palma verifikasi lapangan',
    tahapan: 'Tahap 3',
    status: 'Kelola Mandiri',
    penjelasan: 'Pengelolaan mandiri aktif oleh Regional Kalbar 1',
    luas_ba: 1250.00,
    luas_shp_awal: 1200.00,
    ho_planted_inti: 1000.00,
    ho_planted_plasma: 200.00,
    ho_planted_masyarakat: 0,
    ho_tbm: 50.00,
    ho_areal_lain: 0,
    reg_planted_inti: 1000.00,
    reg_planted_plasma: 200.00,
    reg_planted_masyarakat: 0,
    reg_tbm: 50.00,
    reg_areal_lain: 0,
    inti_dikuasai: 1000.00,
    inti_tidak_dikuasai: 0,
    plasma_dikuasai: 200.00,
    plasma_tidak_dikuasai: 0,
    masyarakat_dikuasai: 0,
    masyarakat_tidak_dikuasai: 0,
    tbm_dikuasai: 50.00,
    tbm_tidak_dikuasai: 0,
    provinsi: 'Kalimantan Barat',
    kabupaten: 'Ketapang',
    ...calculateKebunTotals({
      luas_ba: 1250.00,
      ho_planted_inti: 1000.00,
      ho_planted_plasma: 200.00,
      reg_planted_inti: 1000.00,
      reg_planted_plasma: 200.00,
      inti_dikuasai: 1000.00,
      plasma_dikuasai: 200.00
    })
  }
];

export const INITIAL_MASTER_DATA: MasterDataKebun[] = rawKebunList.map((k) => ({
  ...k,
  created_at: '2026-01-15T08:00:00Z',
  updated_at: '2026-07-20T10:30:00Z'
}));

export const INITIAL_REQUESTS: RequestKebun[] = [
  {
    id: 'req-201',
    request_type: 'UPDATE',
    target_kebun_id: 'kebun-001',
    approval_status: 'PENDING',
    requested_by: DEMO_USERS.aceh.id,
    requested_by_name: DEMO_USERS.aceh.full_name,
    cro: 'CRO 1',
    wilayah: 'Regional Aceh',
    nama_kebun_pt: 'PT Bintang Permata Alue Waki',
    nama_kebun_aktual: 'PT Bintang Permata Alue Waki',
    nama_mitra_vendor: 'CV Aceh Sawit Mandiri',
    kode_tag_kebun: 'PT-BPA-01',
    keterangan: 'Pengajuan KSO Baru pasca penyelesaian klaim masyarakat',
    tahapan: 'Tahap 4',
    status: 'KSO',
    penjelasan: 'Penyelesaian negosiasi dengan mantan kombatan, usulan 30 Ha dikelola KSO',
    luas_ba: 93.54,
    luas_shp_awal: 0,
    ho_planted_inti: 93.54,
    ho_planted_plasma: 0,
    ho_planted_masyarakat: 0,
    ho_tbm: 0,
    ho_areal_lain: 0,
    reg_planted_inti: 93.54,
    reg_planted_plasma: 0,
    reg_planted_masyarakat: 0,
    reg_tbm: 0,
    reg_areal_lain: 0,
    inti_dikuasai: 30.00,
    inti_tidak_dikuasai: 63.54,
    plasma_dikuasai: 0,
    plasma_tidak_dikuasai: 0,
    masyarakat_dikuasai: 0,
    masyarakat_tidak_dikuasai: 0,
    tbm_dikuasai: 0,
    tbm_tidak_dikuasai: 0,
    provinsi: 'Aceh',
    kabupaten: 'Nagan Raya',
    created_at: '2026-07-22T08:15:00Z',
    updated_at: '2026-07-22T08:15:00Z',
    ...calculateKebunTotals({
      luas_ba: 93.54,
      ho_planted_inti: 93.54,
      reg_planted_inti: 93.54,
      inti_dikuasai: 30.00,
      inti_tidak_dikuasai: 63.54
    })
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-001',
    target_role: 'ho',
    title: 'Pengajuan Update KSO Data Kebun',
    message: 'Regional Aceh telah mengajukan permohonan update KSO untuk "PT Bintang Permata Alue Waki".',
    is_read: false,
    link: '/head-office/dashboard',
    created_at: '2026-07-22T08:15:00Z'
  }
];
